/*----------------------------------------------------------
MASV: 19120582, 1920542, 19120521
HO TEN CAC THANH VIEN NHOM: Lê Nhựt Minh, Trần Cẩm Khánh, Lê Nhật Khánh Hưng
LAB: 04 - NHOM
NGAY: 14/05/2022
----------------------------------------------------------*/
--CAU LENH TAO DB
USE master
GO
IF DB_ID('QLSVNhom') IS NOT NULL
	DROP DATABASE QLSVNhom
GO
CREATE DATABASE QLSVNhom
GO
USE QLSVNhom
GO

/*----------------------------------------------------------
MASV: 19120582, 1920542, 19120521
HO TEN CAC THANH VIEN NHOM: Lê Nhựt Minh, Trần Cẩm Khánh, Lê Nhật Khánh Hưng
LAB: 04 - NHOM
NGAY: 14/05/2022
----------------------------------------------------------*/
--CAC CAU LENH TAO TABLE
CREATE TABLE SINHVIEN
(
	MASV NVARCHAR(20),
	HOTEN NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	MALOP VARCHAR(20),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(MAX) NOT NULL
	CONSTRAINT PK_SV
	PRIMARY KEY (MASV)
)

CREATE TABLE NHANVIEN
(
	MANV VARCHAR(20),
	HOTEN NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(20),
	LUONG VARBINARY(MAX),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(MAX) NOT NULL,
	PUBKEY VARCHAR(20)
	CONSTRAINT PK_NV
	PRIMARY KEY (MANV)
)

CREATE TABLE LOP
(
	MALOP VARCHAR(20),
	TENLOP NVARCHAR(100) NOT NULL,
	MANV VARCHAR(20)
	CONSTRAINT PK_L
	PRIMARY KEY (MALOP)
)

CREATE TABLE HOCPHAN
(
	MAHP VARCHAR(20),
	TENHP NVARCHAR(100) NOT NULL,
	SOTC INT
	CONSTRAINT PK_HP
	PRIMARY KEY (MAHP)
)

CREATE TABLE BANGDIEM
(
	MASV NVARCHAR(20),
	MAHP VARCHAR(20),
	DIEMTHI VARBINARY(MAX)
	CONSTRAINT PK_BD
	PRIMARY KEY (MASV, MAHP)
)

ALTER TABLE LOP
ADD
	CONSTRAINT FK_L_NV
	FOREIGN KEY (MANV)
	REFERENCES NHANVIEN
ALTER TABLE SINHVIEN
ADD
	CONSTRAINT FK_SV_L
	FOREIGN KEY (MALOP)
	REFERENCES LOP
ALTER TABLE BANGDIEM
ADD
	CONSTRAINT FK_BD_SV
	FOREIGN KEY (MASV)
	REFERENCES SINHVIEN,
	CONSTRAINT FK_BD_HP
	FOREIGN KEY (MAHP)
	REFERENCES HOCPHAN

/*----------------------------------------------------------
MASV: 19120582, 1920542, 19120521
HO TEN CAC THANH VIEN NHOM: Lê Nhựt Minh, Trần Cẩm Khánh, Lê Nhật Khánh Hưng
LAB: 04 - NHOM
NGAY: 14/05/2022
----------------------------------------------------------*/
-- CAU LENH TAO STORED PROCEDURE
---------i
go
CREATE PROC SP_INS_PUBLIC_ENCRYPT_NHANVIEN @manv VARCHAR(20), @hoten NVARCHAR(100), @email varchar(100), @luongcb VARCHAR(20), @tendn NVARCHAR(100), @matkhau VARCHAR(20), @pub VARCHAR(20)
AS
	DECLARE @AKEY NVARCHAR(max)
	IF ASYMKEY_ID(@pub) IS NULL
    BEGIN
        SET @AKEY = 'CREATE ASYMMETRIC KEY '  + QUOTENAME(@pub) + ' ' +
                 'WITH ALGORITHM = RSA_512 ' + 
                 'ENCRYPTION BY PASSWORD = ' + QUOTENAME(@matkhau , NCHAR(39))
        EXEC (@AKEY)
    END
	DECLARE @matkhauMH varbinary(MAX)
	DECLARE @luongMH varbinary(MAX)
	set @matkhauMH =  CONVERT(varbinary, HashBytes('SHA1',@matkhau))
	set @luongMH= ENCRYPTBYASYMKEY(ASYMKEY_ID(@pub),@luongcb)
	INSERT INTO NHANVIEN(MANV,HOTEN, EMAIL, LUONG, TENDN, MATKHAU, PUBKEY)
	VALUES (@manv, @hoten, @email, @luongMH, @tendn, @matkhauMH, @pub)
GO


EXEC SP_INS_PUBLIC_ENCRYPT_NHANVIEN 'NV01', 'NGUYEN VAN A', 'NVA@', 'LLLLLL', 'NVA', 'MKMKMKMK', 'PUBPUB'
GO
------ii

CREATE PROC SP_SEL_PUBLIC_ENCRYPT_NHANVIEN @manv NVARCHAR(20), @matkhau NVARCHAR(20)
AS
	SELECT MANV, HOTEN, EMAIL, LUONG
	FROM NHANVIEN
	WHERE MANV = @manv
GO 

EXEC SP_SEL_PUBLIC_ENCRYPT_NHANVIEN 'NV01', 'MKMKMKMK'
GO
