USE master
GO
IF DB_ID('QLSV') IS NOT NULL
	DROP DATABASE QLSV
GO
CREATE DATABASE QLSV
GO
USE QLSV
GO

/*----------------------------------------------------------
MASV: 19120582
HO TEN: Lê Nhựt Minh
LAB: 04
NGAY: 13/05/2022
----------------------------------------------------------*/
--CAC CAU LENH TAO TABLE
CREATE TABLE SINHVIEN
(
	MASV NVARCHAR(20),
	HOTEN NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	MALOP VARCHAR(20),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(MAX) NOT NULL
	CONSTRAINT PK_SV
	PRIMARY KEY (MASV)
)

CREATE TABLE NHANVIEN
(
	MANV VARCHAR(20),
	HOTEN NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(20),
	LUONG VARBINARY(MAX),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(MAX) NOT NULL
	CONSTRAINT PK_NV
	PRIMARY KEY (MANV)
)

CREATE TABLE LOP
(
	MALOP VARCHAR(20),
	TENLOP NVARCHAR(100) NOT NULL,
	MANV VARCHAR(20),
	CONSTRAINT PK_L
	PRIMARY KEY (MALOP)
)

ALTER TABLE LOP
ADD
	CONSTRAINT FK_L_NV
	FOREIGN KEY (MANV)
	REFERENCES NHANVIEN
ALTER TABLE SINHVIEN
ADD
	CONSTRAINT FK_SV_L
	FOREIGN KEY (MALOP)
	REFERENCES LOP

/*----------------------------------------------------------
MASV: 19120582
HO TEN: Lê Nhựt Minh
LAB: 04
NGAY: 13/05/2022
----------------------------------------------------------*/

-- tạo MASTER KEY
IF NOT EXISTS
(
	SELECT *
	FROM sys.symmetric_keys
	WHERE symmetric_key_id = 101
)

CREATE MASTER KEY ENCRYPTION BY
	PASSWORD = '123456789'
GO

--tạo CERTIFICATE
IF NOT EXISTS
(
	SELECT *
	FROM sys.certificates
	WHERE name = 'myCert'
)

CREATE CERTIFICATE myCert
	WITH SUBJECT = 'myCert'
GO

CREATE SYMMETRIC KEY PriKey
WITH ALGORITHM = AES_256
ENCRYPTION BY CERTIFICATE myCert
GO

OPEN SYMMETRIC KEY PriKey
DECRYPTION BY CERTIFICATE MyCert
go

-- CAU LENH TAO STORED PROCEDURE
---------i
CREATE PROC SP_INS_ENCRYPT_SINHVIEN @masv NVARCHAR(20), @hoten NVARCHAR(100), @ngaysinh DATETIME, @diachi NVARCHAR(200), @malop VARCHAR(20), @tendn NVARCHAR(100), @matkhau VARCHAR(100)
AS
	DECLARE @matkhau1 varbinary(MAX)
	set @matkhau1 =  CONVERT(varbinary, HashBytes('MD5',@matkhau))
	INSERT INTO SINHVIEN (MASV,HOTEN, NGAYSINH,DIACHI, MALOP, TENDN, MATKHAU)
	VALUES (@masv, @hoten, @ngaysinh, @diachi, @malop, @tendn, @matkhau1)
GO

EXEC SP_INS_ENCRYPT_SINHVIEN 'SV01', 'NGUYEN VAN A', '1/1/1990',
'280 AN DUONG VUONG', NULL, 'NVA', '545045840580458058045804580458435'

SELECT * FROM SINHVIEN

CLOSE SYMMETRIC KEY PriKey

------ii
CREATE SYMMETRIC KEY PriKey1
WITH ALGORITHM = AES_256
ENCRYPTION BY PASSWORD = '19120582'
GO

OPEN SYMMETRIC KEY PriKey1
DECRYPTION BY PASSWORD = '19120582'
go

CREATE PROC SP_INS_ENCRYPT_NHANVIEN @manv NVARCHAR(20), @hoten NVARCHAR(100), @email VARCHAR(20), @luong varchar(20), @tendn NVARCHAR(100), @matkhau VARCHAR(20)
AS
	DECLARE @luongMH varbinary(MAX)
	set @luongMH= ENCRYPTBYKEY(key_GUID('PriKey1'), @luong)
	DECLARE @matkhauMH varbinary(MAX)
	set @matkhauMH = CONVERT(varbinary, HashBytes('SHA1',@matkhau))
	INSERT INTO NHANVIEN (MANV,HOTEN, EMAIL ,LUONG, TENDN, MATKHAU)
	VALUES (@manv, @hoten, @email, @luongMH, @tendn,  @matkhauMH)
GO

EXEC SP_INS_ENCRYPT_NHANVIEN 'NV01', 'NGUYEN VAN A', 'NVA@', 'aaaaaaaa','NVB', 'bbbbbbbb'
SELECT * FROM NHANVIEN

CLOSE SYMMETRIC KEY PriKey1
go
-------iii

CREATE PROC SP_SEL_ENCRYPT_NHANVIEN
AS
	SELECT MANV, HOTEN, EMAIL, LUONG AS LUONGCB
	FROM NHANVIEN
GO

EXEC SP_SEL_ENCRYPT_NHANVIEN
